language: node_js
node_js: stable
addons:
  ssh_known_hosts: 156.251.174.135
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- ssh-add ./deploy_rsa
install:
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install
before_script:
- git config --global user.name "vuhks"
- git config --global user.email "cstg.mutou@gmail.com"
script:
- hexo cl
- hexo g
after_success:
- hexo deploy
branches:
  only:
  - master

