language: node_js
node_js: stable
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_7b1492eb178b_key -iv $encrypted_7b1492eb178b_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
 - chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "vuhks"
- git config --global user.email "cstg.mutou@gmail.com"

install: 
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install
script:
- hexo cl
- hexo g
after_success:
- hexo deploy
branches:
  only:
  - master

