language: node_js
node_js: stable
addons:
  ssh_known_hosts: 156.251.174.135
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
  - yarn add global hexo
  - yarn add global hexo-cli
  - yarn add global hexo-deployer-git

script:
- hexo cl
- hexo d -g


branches:
  only:
  - master

